import { DawatTheme } from '../types';

export const THEME_CATEGORIES = [
  'Trending', 'Ramadan', 'Eid', 'Sisters', 'Brothers',
  'Family', 'Nikah', 'Iftar', 'Scholars', 'Minimal',
  'Eclectic', 'Elegant', 'Community',
] as const;

export const THEMES: DawatTheme[] = [
  {
    id: 'ramadan_kareem',
    name: 'Ramadan Kareem',
    categories: ['Trending', 'Ramadan'],
    bannerBg: '#0A1628',
    bannerBgImage: 'linear-gradient(135deg, #0A1628 0%, #1A2744 50%, #0D1B33 100%)',
    accentColor: '#C9A84C',
    textColor: '#FFFFFF',
    tagBg: '#1A2744',
    tagColor: '#C9A84C',
    defaultEmoji: '🌙',
  },
  {
    id: 'eid_gala',
    name: 'Eid Gala',
    categories: ['Trending', 'Eid'],
    bannerBg: '#0D0D0D',
    bannerBgImage: 'linear-gradient(135deg, #0D0D0D 0%, #1A1A1A 40%, #2A1F0A 100%)',
    accentColor: '#F0C040',
    textColor: '#FFFFFF',
    tagBg: '#2A1F0A',
    tagColor: '#F0C040',
    defaultEmoji: '✨',
  },
  {
    id: 'iftar_party',
    name: 'Iftar Party',
    categories: ['Trending', 'Iftar'],
    bannerBg: '#2A1505',
    bannerBgImage: 'linear-gradient(135deg, #2A1505 0%, #4A2810 50%, #3A1A08 100%)',
    accentColor: '#F59E0B',
    textColor: '#FFFFFF',
    tagBg: '#4A2810',
    tagColor: '#F59E0B',
    defaultEmoji: '🏮',
  },
  {
    id: 'sisters_halaqa',
    name: 'Sisters Halaqa',
    categories: ['Sisters', 'Trending'],
    bannerBg: '#1A0A1E',
    bannerBgImage: 'linear-gradient(135deg, #1A0A1E 0%, #2D1233 50%, #3D1544 100%)',
    accentColor: '#D4A0D9',
    textColor: '#FFFFFF',
    tagBg: '#2D1233',
    tagColor: '#D4A0D9',
    defaultEmoji: '🌸',
  },
  {
    id: 'nikah',
    name: 'Nikah Invitation',
    categories: ['Nikah', 'Elegant'],
    bannerBg: '#F5F0E8',
    bannerBgImage: 'linear-gradient(135deg, #F5F0E8 0%, #EDE5D5 50%, #E8DCCA 100%)',
    accentColor: '#8B6914',
    textColor: '#2C1810',
    tagBg: '#E8DCCA',
    tagColor: '#8B6914',
    defaultEmoji: '💍',
  },
  {
    id: 'masjid_event',
    name: 'Masjid Event',
    categories: ['Community', 'Trending'],
    bannerBg: '#0A2218',
    bannerBgImage: 'linear-gradient(135deg, #0A2218 0%, #0F3325 50%, #144430 100%)',
    accentColor: '#4CAF50',
    textColor: '#FFFFFF',
    tagBg: '#0F3325',
    tagColor: '#4CAF50',
    defaultEmoji: '🕌',
  },
  {
    id: 'arabic_nights',
    name: 'Arabic Nights',
    categories: ['Trending', 'Elegant'],
    bannerBg: '#1A1005',
    bannerBgImage: 'linear-gradient(135deg, #1A1005 0%, #2A1A08 50%, #3A2A10 100%)',
    accentColor: '#C9A84C',
    textColor: '#FFFFFF',
    tagBg: '#2A1A08',
    tagColor: '#C9A84C',
    defaultEmoji: '🪔',
  },
  {
    id: 'desert_sunset',
    name: 'Desert Sunset',
    categories: ['Eclectic', 'Trending'],
    bannerBg: '#1A0A05',
    bannerBgImage: 'linear-gradient(180deg, #4A1A08 0%, #8B3A15 40%, #C96830 70%, #E8A060 100%)',
    accentColor: '#E8A060',
    textColor: '#FFFFFF',
    tagBg: '#4A1A08',
    tagColor: '#E8A060',
    defaultEmoji: '🌅',
  },
  {
    id: 'brothers_night',
    name: 'Brothers Night',
    categories: ['Brothers'],
    bannerBg: '#050A1A',
    bannerBgImage: 'linear-gradient(135deg, #050A1A 0%, #0A1433 50%, #102050 100%)',
    accentColor: '#60A5FA',
    textColor: '#FFFFFF',
    tagBg: '#0A1433',
    tagColor: '#60A5FA',
    defaultEmoji: '💪',
  },
  {
    id: 'laylatul_qadr',
    name: 'Laylatul Qadr',
    categories: ['Ramadan', 'Elegant'],
    bannerBg: '#0D0520',
    bannerBgImage: 'linear-gradient(180deg, #0D0520 0%, #1A0A3A 40%, #2A1055 100%)',
    accentColor: '#D4A0FF',
    textColor: '#FFFFFF',
    tagBg: '#1A0A3A',
    tagColor: '#D4A0FF',
    defaultEmoji: '⭐',
  },
  {
    id: 'family_picnic',
    name: 'Family Picnic',
    categories: ['Family', 'Community'],
    bannerBg: '#1A1A08',
    bannerBgImage: 'linear-gradient(180deg, #87CEEB 0%, #90EE90 60%, #228B22 100%)',
    accentColor: '#2E7D32',
    textColor: '#FFFFFF',
    tagBg: '#2E7D32',
    tagColor: '#FFFFFF',
    defaultEmoji: '🌳',
  },
  {
    id: 'scholar_talk',
    name: 'Scholar Talk',
    categories: ['Scholars', 'Community'],
    bannerBg: '#0A1A0A',
    bannerBgImage: 'linear-gradient(135deg, #0A1A0A 0%, #133313 50%, #1A4A1A 100%)',
    accentColor: '#81C784',
    textColor: '#FFFFFF',
    tagBg: '#133313',
    tagColor: '#81C784',
    defaultEmoji: '📚',
  },
  {
    id: 'geometric_blue',
    name: 'Geometric Blue',
    categories: ['Elegant', 'Minimal'],
    bannerBg: '#050A1A',
    bannerBgImage: 'linear-gradient(135deg, #050A1A 0%, #0D1833 50%, #152550 100%)',
    accentColor: '#4A90D9',
    textColor: '#FFFFFF',
    tagBg: '#0D1833',
    tagColor: '#4A90D9',
    defaultEmoji: '🔷',
  },
  {
    id: 'islamic_stars',
    name: 'Islamic Stars',
    categories: ['Elegant', 'Eid'],
    bannerBg: '#0D0D0D',
    bannerBgImage: 'linear-gradient(135deg, #0D0D0D 0%, #1A1A1A 50%, #252525 100%)',
    accentColor: '#C9A84C',
    textColor: '#FFFFFF',
    tagBg: '#1A1A1A',
    tagColor: '#C9A84C',
    defaultEmoji: '⭐',
  },
  {
    id: 'walima',
    name: 'Walima',
    categories: ['Nikah', 'Elegant'],
    bannerBg: '#1A0A0F',
    bannerBgImage: 'linear-gradient(135deg, #1A0A0F 0%, #3A1520 50%, #4A1A2A 100%)',
    accentColor: '#E8A0B0',
    textColor: '#FFFFFF',
    tagBg: '#3A1520',
    tagColor: '#E8A0B0',
    defaultEmoji: '🌹',
  },
  {
    id: 'hajj_journey',
    name: 'Hajj Journey',
    categories: ['Community', 'Scholars'],
    bannerBg: '#0D0D05',
    bannerBgImage: 'linear-gradient(180deg, #0D0D05 0%, #1A1A0A 40%, #2A2510 100%)',
    accentColor: '#C9A84C',
    textColor: '#FFFFFF',
    tagBg: '#1A1A0A',
    tagColor: '#C9A84C',
    defaultEmoji: '🕋',
  },
  {
    id: 'minimal_crescent',
    name: 'Minimal Crescent',
    categories: ['Minimal', 'Elegant'],
    bannerBg: '#F5F0E8',
    bannerBgImage: 'linear-gradient(135deg, #F5F0E8 0%, #EDE5D5 100%)',
    accentColor: '#1A1A1A',
    textColor: '#1A1A1A',
    tagBg: '#E0D8C8',
    tagColor: '#1A1A1A',
    defaultEmoji: '🌙',
  },
  {
    id: 'eid_adha',
    name: 'Eid ul-Adha',
    categories: ['Eid', 'Family'],
    bannerBg: '#0A1A0A',
    bannerBgImage: 'linear-gradient(135deg, #0A1A0A 0%, #0F2E0F 50%, #154015 100%)',
    accentColor: '#66BB6A',
    textColor: '#FFFFFF',
    tagBg: '#0F2E0F',
    tagColor: '#66BB6A',
    defaultEmoji: '🐑',
  },
  {
    id: 'dark_ramadan',
    name: 'Dark Ramadan',
    categories: ['Ramadan', 'Eclectic'],
    bannerBg: '#0A0515',
    bannerBgImage: 'linear-gradient(180deg, #0A0515 0%, #150A25 50%, #1A0F30 100%)',
    accentColor: '#B388FF',
    textColor: '#FFFFFF',
    tagBg: '#150A25',
    tagColor: '#B388FF',
    defaultEmoji: '🌌',
  },
  {
    id: 'ornate_invitation',
    name: 'Ornate Invitation',
    categories: ['Elegant', 'Nikah'],
    bannerBg: '#F8F3E8',
    bannerBgImage: 'linear-gradient(135deg, #F8F3E8 0%, #F0E8D5 50%, #E8DDCA 100%)',
    accentColor: '#8B6914',
    textColor: '#2C1810',
    tagBg: '#E8DDCA',
    tagColor: '#8B6914',
    defaultEmoji: '📜',
  },
];

export function getThemeById(id: string): DawatTheme | undefined {
  return THEMES.find((t) => t.id === id);
}

export function getThemesByCategory(category: string): DawatTheme[] {
  if (category === 'Trending') {
    return THEMES.filter((t) => t.categories.includes('Trending'));
  }
  return THEMES.filter((t) => t.categories.includes(category));
}
